sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "1234"
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRKzFP2HhP7AC6bKFNs
    access-key-secret: MGpnBb7fBAki6XdcefCr1NqKrqm1g2
    bucket-name: sky-take-out-violet
  redis:
    host: localhost
    port: 6379
#    password: 123456
#    database: 10
  wechat:
    appid: wxe90aa46ba100d812
    secret: 141bfb5a337afadd1a4d413e24ee2d0d
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
